### ISSUE TITLE
Exception occurs if "Stay logged in" is true

### ISSUE THREAD

**Issue by snolan-uturn** [aws-azure-login/aws-azure-login#103]
I'm seeing this exception after setting "Stay logged in" to true - the exception does not occur if "Stay logged in" is false:
`(node:8900) UnhandledPromiseRejectionWarning: Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (C:\Users\username\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\ws\lib\websocket.js:329:19)
    at WebSocketTransport.send (C:\Users\username\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\WebSocketTransport.js:60:14)
    at Connection._rawSend (C:\Users\username\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\Connection.js:86:21)
    at Connection.send (C:\Users\username\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\Connection.js:72:21)
    at gracefullyCloseChrome (C:\Users\username\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\Launcher.js:200:20)
    at Browser.close (C:\Users\username\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\Browser.js:255:31)
    at Browser.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\helper.js:112:23)
    at Object._performLoginAsync (C:\Users\username\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:530:34)
    at async Object.loginAsync (C:\Users\username\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:281:30)
(node:8900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated 
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

The login works even after the exception occurs.

**Comment by larsschumachenko** [comment]
I can reproduce it, and I guess I even introduced it. Will provide a fix.

**Comment by kennethaasan** [comment]
Fix released in v1.13.2
