### ISSUE TITLE
Workaround for Error: No node found for selector: input[name="loginfmt"]

### ISSUE THREAD

**Issue by nickbeaugie** [aws-azure-login/aws-azure-login#106]
I want to share a workaround to an issue I had.

Here is my PowerShell output.
```
PS C:\> aws-azure-login                                                                                                                                        Logging in with profile 'default'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
? Username: myusername@mycompany.co.uk
Error: No node found for selector: input[name="loginfmt"]
    at assert (C:\Users\myusername\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\helper.js:279:11)
    at DOMWorld.focus (C:\Users\myusername\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\DOMWorld.js:376:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.handler (C:\Users\myusername\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:64:13)
    at async Object._performLoginAsync (C:\Users\myusername\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:499:29)
    at async Object.loginAsync (C:\Users\myusername\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:281:30)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\myusername\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.focus (C:\Users\myusername\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\Page.js:1044:29)
    at Object.handler (C:\Users\myusername\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:64:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object._performLoginAsync (C:\Users\myusername\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:499:29)
    at async Object.loginAsync (C:\Users\myusername\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:281:30)
```
For some reason, my account is configued in such a way that my credentials are cached - and I don't receive the prompt for password - instead, I immediately get the MFA prompt on my phone, I confirm it, but then I get this stack of errors.

The workaround is to run in GUI mode instead.
`aws-azure-login --mode=gui `

Now I get a popup window on my machine telling me that I'm getting a prompt on my phone. I don't need to interact with the window in any way, I just confirm MFA, then the script resumes getting my AWS credentials.

**Comment by kennethaasan** [comment]
I guess this can happen with some SAML solutions with a custom layout? Feel free to try to debug this and submit a PR

**Comment by nickbeaugie** [comment]
To be honest, since discovering the workaround, it works so well for me that I don't really think this needs fixing.

All I wanted was, for anyone else who has this problem, when they Google for the error message, that they could find somewhere like this page, describing the workaround.

I'm a bit new to GitHub actually. If i close this issue, will the page still hang around and fulfill the purpose I describe above?

**Comment by kennethaasan** [comment]
Yes, it should. I'm closing

**Comment by nickbeaugie** [comment]
No problem!
