### ISSUE TITLE
Error using aws-azure-login container on WSL 2

### ISSUE THREAD

**Issue by mchassy** [aws-azure-login/aws-azure-login#108]
I have installed Ubuntu 18.04 as a WSL on my Windows 10 laptop.
Windows version and build `Version 2004 (OS Build 19035.1)`
Docker Edge version `2.1.6.1`

I realise that you said that this may be brittle based on windows updates and I am using the bleeding edge version. But can you see any reason why this would not be working?

Method of accessing docker from the WSL
```
export DOCKERPATH="/mnt/c/Program\ Files/Docker/Docker/resources/bin"
alias docker="$DOCKERPATH/docker.exe"
```
Method of invoking aws-azure-login config
```
docker run --rm -it -v ~/.aws:/root/.aws sportradar/aws-azure-login --configure
```
This works fine.

Method of invoking aws-azure-login
```
docker run --rm -it -v ~/.aws:/root/.aws sportradar/aws-azure-login
```
Error
```
❯ docker run --rm -it -v ~/.aws:/root/.aws sportradar/aws-azure-login
Logging in with profile 'default'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
? Username: mark.chassy@virtualclarity.com
? Password: [hidden]
We've sent a notification to your mobile device. Please open the Microsoft Authenticator app to respond.
Unable to recognize page state! A screenshot has been dumped to aws-azure-login-unrecognized-state.png. If this problem persists, try runn
ing with --mode=gui or --mode=debug
```

Attempt with --mode=gui
```
❯ docker run --rm -it -v ~/.aws:/root/.aws sportradar/aws-azure-login --mode=gui
Logging in with profile 'default'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
Error: Failed to launch chrome!

(chrome:15): Gtk-WARNING **: cannot open display:


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:348:14)
    at ChildProcess.helper.addEventListener (/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:338:60)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

Attempt with --mode=debug
```❯ docker run --rm -it -v ~/.aws:/root/.aws sportradar/aws-azure-login --mode=debug
Logging in with profile 'default'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
Error: Failed to launch chrome!

(chrome:15): Gtk-WARNING **: cannot open display:


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:348:14)
    at ChildProcess.helper.addEventListener (/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:338:60)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

```

**Comment by mchassy** [comment]
I have also tried using powershell and CMD and get the same errors.

**Comment by kennethaasan** [comment]
Hi @mchassy,

I'll try to have a look at this next week. I haven't tested the docker image since we took over the maintenance of this tool.

**Comment by jlzg** [comment]
you can try this command

```
aws-azure-login --mode=gui --mode=debug --no-sandbox  --enable-chrome-network-service  --no-verify-ssl
```

**Comment by mchassy** [comment]
Hi @lwpro2 
Thanks for the suggestion. But I have moved to a linux laptop (Ubuntu) and on the laptop, I don't have this problem at all.

**Comment by flomsk** [comment]
> you can try this command
> 
> ```
> aws-azure-login --mode=gui --mode=debug --no-sandbox  --enable-chrome-network-service  --no-verify-ssl
> ```

for me it doenst work.
but it will be great to have solution for WSL

**Comment by mathewwallminfos** [comment]
Im afriad this is not working for me either:

```
aws-azure-login --mode=gui --mode=debug --no-sandbox  --enable-chrome-network-service  --no-verify-ssl --profile qa
Logging in with profile 'qa'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
Error: Failed to launch the browser process!
[643:648:0603/151110.437069:ERROR:file_path_watcher_linux.cc(71)] Failed to read /proc/sys/fs/inotify/max_user_watches
[643:643:0603/151110.457320:ERROR:browser_main_loop.cc(1512)] Unable to open X display.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:750:14)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:740:61)
    at ChildProcess.emit (events.js:327:22)
    at ChildProcess.EventEmitter.emit (domain.js:485:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

**Comment by ralphcoder99** [comment]
I was able to get it to work by installing this and running 
https://stackoverflow.com/questions/60304251/unable-to-open-x-display-when-trying-to-run-google-chrome-on-centos-rhel-7-5

Then I ran this command:
aws-azure-login --mode=gui --mode=debug --no-sandbox  --enable-chrome-network-service  --no-verify-ssl

worked for me, hope that helps

**Comment by dmeiser** [comment]
I've been puzzling over this post for a long time, trying to get this fully working. I have it working without a problem with our MFA provider. From what I've seen, there are 2 basic ways to get this working with WSL2. The long way and the short way.

The short way:
- Setup your MFA provider send you a push notification any and every time you login. I've done this with 2 different MFA providers, I don't think the MFA provider matters. Just have it send you a push notification automatically.
- Use Docker integration.
- You don't have to use any modes or sandobx. It Just Works (TM).

The long way (see @ralphcoder99 above):
- Setup a minimal X environment and export the display
- Install an X server in windows
- Use --mode=gui to open a Chrome window and use the browser to login.

**Comment by MarcelJoubert** [comment]
So very late reply, but in my case the --no-prompt flag worked. Just thought I might post if someone runs into this again.
Example command: aws-azure-login --profile dev --no-prompt --mode=gui
