### ISSUE TITLE
Issue use aws-azure-login command with Window 7

### ISSUE THREAD

**Issue by Pranethm** [aws-azure-login/aws-azure-login#111]
Hi

I am getting below error when trying to run log in command
**aws-azure-login --profile xxxx**
Here is my environment: Window 7, Node v12.14.1

Please help

Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (C:\Users\test\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\JSHandle.js:217:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async ElementHandle.click (C:\Users\test\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\JSHandle.js:283:20)
    at async DOMWorld.click (C:\Users\test\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\DOMWorld.js:367:5)
    at async Object.handler (C:\Users\test\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:76:13)
    at async Object._performLoginAsync (C:\Users\test\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:495:29)
    at async Object.loginAsync (C:\Users\test\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:284:30)
  -- ASYNC --
    at ElementHandle.<anonymous> (C:\Users\test\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.click (C:\Users\test\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\DOMWorld.js:367:18)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.handler (C:\Users\test\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:76:13)
    at async Object._performLoginAsync (C:\Users\test\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:495:29)
    at async Object.loginAsync (C:\Users\test\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:284:30)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\test\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.click (C:\Users\test\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\Page.js:1037:29)
    at Object.handler (C:\Users\test\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:76:24)
    at async Object._performLoginAsync (C:\Users\test\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:495:29)
    at async Object.loginAsync (C:\Users\test\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:284:30)

**Comment by kennethaasan** [comment]
Hi @Pranethm,

Can you try to run with debug mode (https://github.com/sportradar/aws-azure-login#troubleshooting) and let me know where it fails?
Also, none of us maintainers are using Windows, so I would appreciate it if you can file a PR with a fix.

**Comment by arikbidny** [comment]
Hey,
try to run it like this:
aws-azure-login --mode gui --no-disable-extensions
