### ISSUE TITLE
configureProfileAsync.js:8  error on Windows 10 

### ISSUE THREAD

**Issue by haim-n** [aws-azure-login/aws-azure-login#120]
Installed without errors  using - 
npm install -g aws-azure-login

using --mode debug didn't help. same error output. 

C:\Users\User>aws-azure-login --configure
C:\Users\User\AppData\Roaming\npm\node_modules\aws-azure-login\lib\configureProfileAsync.js:8
async function configureProfileAsync(profileName) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\aws-azure-login\lib\index.js:10:33)

**Comment by kennethaasan** [comment]
Looks like you're using an old version of node that `aws-azure-login` doesn't support. You need at least node version 8.
