### ISSUE TITLE
Using `httpOptions.proxy` instead of `httpOptions.agent`

### ISSUE THREAD

**Issue by andrew8088** [aws-azure-login/aws-azure-login#123]
I was having trouble assuming the role from behind my corporate proxy. Here's the error I was getting:

```
{ Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.EventEmitter.emit (domain.js:441:20)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
  message: 'unable to get local issuer certificate',
  code: 'NetworkingError',
  region: 'us-east-1',
  hostname: 'sts.amazonaws.com',
  retryable: true,
  time: 2020-03-04T13:33:31.097Z }
```

I played around with the code for a while, and found something that worked:

```diff
// login.js - _assumeRoleAsync

if (process.env.https_proxy) {
  AWS.config.update({
    httpOptions: {
-     agent: proxy(process.env.https_proxy)
+     proxy: process.env.https_proxy
    }
  });
}
```

I don't really know enough about how proxies work to know what's the difference here, so I'm not sure if this is worth changing or not (happy to submit a PR if you think so). But I figured I'd leave a note about this, just in case someone else has a similar issue.

**Comment by fractionalJoe** [comment]
I'm having this issue. is there a work around?

**Comment by andrew8088** [comment]
@fractionalJoe  I'm no longer using this project, but at the time, I just made the above modification to the code locally.

**Comment by fractionalJoe** [comment]
Thanks @andrew8088.
