### ISSUE TITLE
Error: aws-azure-login version 2.2.4 SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by mfarrokhnia** [aws-azure-login/aws-azure-login#147]
I have installed aws-azure-login on a linux server-ubuntu for all users, however when I run the aws-azure-login command I get this error:

$sudo npm install -g aws-azure-login --unsafe-perm
.....
/usr/local/bin/aws-azure-login -> /usr/local/lib/node_modules/aws-azure-login/lib/index.js
+ aws-azure-login@2.2.4

$ sudo chmod -R go+rx $(sudo npm root -g)

$ aws-azure-login
/usr/local/lib/node_modules/aws-azure-login/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/aws-azure-login/lib/login.js:13:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/aws-azure-login/lib/index.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)

system info:

$ aws --version
aws-cli/1.18.69 Python/3.6.9 Linux/5.3.0-1034-aws botocore/1.16.19
$ npm --version
3.5.2

**Comment by mfarrokhnia** [comment]
I've updated node version to the latest version (v12.18.3) and then re-installed aws-azure-login which fixed the issue.
