### ISSUE TITLE
errno: 'EACCES', syscall: 'spawn'

### ISSUE THREAD

**Issue by ghost** [aws-azure-login/aws-azure-login#15]
I updated to the most recent version of the tool. I get the following error:

gbaz@DESKTOP-EPRVA20:~$ aws-azure-login
Logging in with profile 'default'...
{ Error: spawn EACCES
    at _errnoException (util.js:1021:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at Object.exports.spawn (child_process.js:494:9)
    at Function.launch (/usr/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:98:40)
    at <anonymous> code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }

Below is the install process

gbaz@DESKTOP-EPRVA20:~$ sudo npm install -g aws-azure-login --unsafe-perm
/usr/bin/aws-azure-login -> /usr/lib/node_modules/aws-azure-login/bin/index.js

> puppeteer@0.13.0 install /usr/lib/node_modules/aws-azure-login/node_modules/puppeteer
> node install.js

Downloading Chromium r515411 - 95.4 Mb [====================] 100% 0.0s
Chromium downloaded to /usr/lib/node_modules/aws-azure-login/node_modules/puppeteer/.local-chromium/linux-515411
+ aws-azure-login@1.0.0
added 51 packages and updated 55 packages in 121.821s

**Comment by dtjohnson** [comment]
That's a Linux permissions issue. Your user doesn't have permissions to the /usr/lib/node_modules directory. You'll need to give your user read access (recursively).

**Comment by ghost** [comment]
I have tried to change the permissions as follows which seems to have fixed the **EACCES', errno: 'EACCES', syscall: 'spawn' error**

chmod go+rx /usr/lib/node_modules/ -R


However, now I am getting this new error code: **'ESRCH', errno: 'ESRCH', syscall: 'kill'**

(env1) gbaz@DESKTOP-EPRVA20:~$ aws-azure-login --mode gui
Logging in with profile 'default'...
{ Error: kill ESRCH
    at Object._errnoException (util.js:1021:11)
    at process.kill (internal/process.js:180:18)
    at forceKillChrome (/usr/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:162:19)
    at killChrome (/usr/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:147:9)
    at Function.launch (/usr/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:137:7)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) code: 'ESRCH', errno: 'ESRCH', syscall: 'kill' }

**Comment by dtjohnson** [comment]
It seems puppeteer [doesn't play well](https://github.com/GoogleChrome/puppeteer/issues/375) with npm global installs to /usr. You'll need to globally install to the user home directory using [these instructions](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory). I just tried it on an Ubuntu instance and it works fine.

**Comment by gbaz2000** [comment]
I followed these steps

$ mkdir ~/.npm-global
$  npm config set prefix '~/.npm-global'
added '$HOME/.npm-global' to the .profile file where $HOME=/home/gbaz
$ source ~/.profile

$ npm install -g aws-azure-login
/home/gbaz/.npm-global/bin/aws-azure-login -> /home/gbaz/.npm-global/lib/node_modules/aws-azure-login/bin/index.js

> puppeteer@0.13.0 install /home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer
> node install.js

Downloading Chromium r515411 - 95.4 Mb [====================] 100% 0.0s
Chromium downloaded to /home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/.local-chromium/linux-515411
+ aws-azure-login@1.0.1
added 106 packages in 134.813s

gbaz@DESKTOP-EPRVA20:~$ aws-azure-login
Logging in with profile 'default'...
{ Error: kill ESRCH
    at Object._errnoException (util.js:1021:11)
    at process.kill (internal/process.js:180:18)
    at forceKillChrome (/home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:162:19)
    at killChrome (/home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:147:9)
    at Function.launch (/home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:137:7)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) code: 'ESRCH', errno: 'ESRCH', syscall: 'kill' }

**Comment by dtjohnson** [comment]
That's progress, I suppose. Can you please make sure you have all of the puppeteer dependencies installed: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch

**Comment by gbaz2000** [comment]
Checked the dependencies there were a few missing so I installed them, updated npm and reinstalled the tool but still getting the error :(

gbaz@DESKTOP-EPRVA20:~$ npm i -g npm
/home/gbaz/.npm-global/bin/npm -> /home/gbaz/.npm-global/lib/node_modules/npm/bin/npm-cli.js
/home/gbaz/.npm-global/bin/npx -> /home/gbaz/.npm-global/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.5.1
added 460 packages in 88.918s

gbaz@DESKTOP-EPRVA20:~$ npm install -g aws-azure-login
/home/gbaz/.npm-global/bin/aws-azure-login -> /home/gbaz/.npm-global/lib/node_modules/aws-azure-login/bin/index.js

> puppeteer@0.13.0 install /home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer
> node install.js

Downloading Chromium r515411 - 95.4 Mb [====================] 100% 0.0s
Chromium downloaded to /home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/.local-chromium/linux-515411
+ aws-azure-login@1.0.1
added 106 packages in 93.44s

gbaz@DESKTOP-EPRVA20:~$ aws-azure-login
Logging in with profile 'default'...
{ Error: kill ESRCH
    at Object._errnoException (util.js:1024:11)
    at process.kill (internal/process.js:183:18)
    at forceKillChrome (/home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:162:19)
    at killChrome (/home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:147:9)
    at Function.launch (/home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:137:7)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) code: 'ESRCH', errno: 'ESRCH', syscall: 'kill' }
