### ISSUE TITLE
Unexpected Identifier in configureProfileAsync

### ISSUE THREAD

**Issue by jfk2000** [aws-azure-login/aws-azure-login#16]
Hi,

First time install of aws-azure-login@1.0.1 

Following install instructions when i get to the following it doesn't like it. 

> aws-azure-login --configure
> /usr/lib/node_modules/aws-azure-login/lib/configureProfileAsync.js:6
> module.exports = async profileName => {
>                        ^^^^^^^^^^^
> SyntaxError: Unexpected identifier
>     at Object.exports.runInThisContext (vm.js:76:16)
>     at Module._compile (module.js:542:28)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/usr/lib/node_modules/aws-azure-login/bin/index.js:10:31)
>     at Module._compile (module.js:570:32)

Any ideas ?

**Comment by jfk2000** [comment]
upgrading to Node 9.2 fixed it from 6.9 . ye si should have read the closed issues first :-)
