### ISSUE TITLE
'ESRCH', errno: 'ESRCH', syscall: 'kill'

### ISSUE THREAD

**Issue by ghost** [aws-azure-login/aws-azure-login#17]
I followed these steps

1- Made sure I have all of the puppeteer dependencies installed: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch

2- Changed NPM's default directory to my user's home directory: 

https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory

Then performed the below steps

**gbaz@DESKTOP-EPRVA20:~$ npm i -g npm**
/home/gbaz/.npm-global/bin/npm -> /home/gbaz/.npm-global/lib/node_modules/npm/bin/npm-cli.js
/home/gbaz/.npm-global/bin/npx -> /home/gbaz/.npm-global/lib/node_modules/npm/bin/npx-cli.js

npm@5.5.1
added 460 packages in 88.918s

**gbaz@DESKTOP-EPRVA20:~$ npm install -g aws-azure-login**
/home/gbaz/.npm-global/bin/aws-azure-login -> /home/gbaz/.npm-global/lib/node_modules/aws-azure-login/bin/index.js

puppeteer@0.13.0 install /home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer
node install.js
Downloading Chromium r515411 - 95.4 Mb [====================] 100% 0.0s
Chromium downloaded to /home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/.local-chromium/linux-515411

aws-azure-login@1.0.1
added 106 packages in 93.44s

**gbaz@DESKTOP-EPRVA20:~$ aws-azure-login**
Logging in with profile 'default'...
{ Error: kill ESRCH
at Object._errnoException (util.js:1024:11)
at process.kill (internal/process.js:183:18)
at forceKillChrome (/home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:162:19)
at killChrome (/home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:147:9)
at Function.launch (/home/gbaz/.npm-global/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:137:7)
at 
at process._tickDomainCallback (internal/process/next_tick.js:228:7) code: 'ESRCH', errno: 'ESRCH', syscall: 'kill' }

**Comment by dtjohnson** [comment]
I added some improved install instructions for Linux. I also set up a Docker image that should make it much easier to use in Linux. Hope it helps!

**Comment by ghost** [comment]
Followed these steps for the install

sudo npm install -g aws-azure-login --unsafe-perm

sudo chmod -R go+rx $(npm root -g)

aws-azure-login --configure --profile xyz

Up to this point no errors what so ever

gbaz@DESKTOP-EPRVA20:~$ aws-azure-login --profile xyz
Logging in with profile 'xyz'...
{ Error: kill ESRCH
    at Object._errnoException (util.js:1022:11)
    at process.kill (internal/process.js:183:18)
    at forceKillChrome (/home/gbaz/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:169:19)
    at Function.launch (/home/gbaz/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:144:7)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) code: 'ESRCH', errno: 'ESRCH', syscall: 'kill' }

gbaz@DESKTOP-EPRVA20:~$ which node
/usr/bin/node
gbaz@DESKTOP-EPRVA20:~$ which npm
/usr/bin/npm
gbaz@DESKTOP-EPRVA20:~$ nodejs -v
v8.9.4
gbaz@DESKTOP-EPRVA20:~$ npm -v
5.6.0

**Comment by dtjohnson** [comment]
Try running with the --no-sandbox flag

**Comment by ghost** [comment]
$ aws-azure-login --no-sandbox
Unable to recognize page state! A screenshot has been dumped to aws-azure-login-unrecognized-state.png. If this problem persists, try running with --mode=gui or --mode=debug

$ aws-azure-login --no-sandbox --mode=gui
Error: Failed to launch chrome!

    at onClose (/home/gbaz/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:226:14)
    at ChildProcess.helper.addEventListener (/home/gbaz/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:216:60)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

$ aws-azure-login --mode=gui 

{ Error: kill ESRCH
    at Object._errnoException (util.js:1022:11)
    at process.kill (internal/process.js:183:18)
    at forceKillChrome (/home/gbaz/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:169:19)
    at Function.launch (/home/gbaz/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Launcher.js:144:7)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) code: 'ESRCH', errno: 'ESRCH', syscall: 'kill' }

**Comment by dtjohnson** [comment]
Hey, well that's progress. The GUI mode won't work unless you have a GUI desktop. It does look like first command sort of worked. It successfully launched Chrome but the page it loaded wasn't recognized. Could you upload that debug screenshot it created?

**Comment by ghost** [comment]
![inkedaws-azure-login-unrecognized-state_li](https://user-images.githubusercontent.com/32670159/35076226-5cdef1ce-fc4b-11e7-9479-1ad8d43d32f8.jpg)


It looks like a redirected ADFS page from AzureAD

**Comment by dtjohnson** [comment]
Ah. Well, it is working correctly. ADFS isn't currently supported. It should definitely be possible and much easier with the new state detection model, but I don't have an ADFS setup to do it. There were some forks from the previous version for this but no PRs ever came through.

**Comment by dtjohnson** [comment]
Closing as duplicate of #12.
