### ISSUE TITLE
Proxy configuration behind a corpororate proxy

### ISSUE THREAD

**Issue by tubezleb** [aws-azure-login/aws-azure-login#171]
Hello,

Following the documentation I set the environnement variable https_proxy but after that i'm facing an error:

`TypeError: You must specify a "protocol" for the proxy type (http, https, socks, socks4, socks4a, socks5, socks5h, pac+data, pac+file, pac+ftp, pac+http, pac+https)
    at mapOptsToProxy (C:\Users\username\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\proxy-agent\index.js:100:11)
    at new ProxyAgent (C:\Users\username\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\proxy-agent\index.js:150:17)
    at Object.ProxyAgent [as default] (C:\Users\username\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\proxy-agent\index.js:145:45)
    at Object._assumeRoleAsync (C:\Users\username\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:708:49)
    at Object.loginAsync (C:\Users\username\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:327:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

How can I specify the protocol?

Thanks

**Comment by tubezleb** [comment]
No one?

**Comment by kennethaasan** [comment]
@tubezleb,

I've never used a proxy, but the error message says you need to specify a protocol for your proxy. If _https_, probably add `https://`?
