### ISSUE TITLE
Windows aws-azure-login.cmd not returning json when used in awscli credential_process

### ISSUE THREAD

**Issue by dgmhn** [aws-azure-login/aws-azure-login#185]
In Windows, when using a credential_provider in the awscli config, the first time you run an AWS command and it has to login, you get an error Expecting value: line 1 column 1 (char 0). Subsequent command runs work as expected.

The awscli expects the provider to return a json output. https://docs.aws.amazon.com/sdkref/latest/guide/setting-global-credential_process.html  (see "expected output from credentials program"). I don't think aws-azure-login.cmd is doing that. I think it is only writing to the credentials file. That is why subsequent calls work.

Sample of entry in config file  (%USERPROFILE%\.aws\config)
[profile legacy]
region=us-east-1
output=json
azure_tenant_id=XXXXXXXX
azure_app_id_uri=XXXXXXXX
azure_default_username=<username>
azure_default_role_arn=arn:aws:iam::<account#>:role/my-role
azure_default_duration_hours=1
cli_pager=
credential_process="c:\users\me\AppData\Roaming\npm\aws-azure-login.cmd" --profile legacy --mode gui --no-prompt

Steps to reproduce
1. Delete your credentials file %USERPROFILE%\.aws\credentials
2. Configure credential_process
3. Open a command prompt (command or powershell)
4. Run an aws command. for example: aws sts get-caller-identity --profile legacy
5. (You'll see aws-azure-login.cmd log you in) In your shell you'll get error: Expecting value: line 1 column 1 (char 0)
6. Look at your credentials file, you'll now see the credentials.
7. Run the command again and it will succeed (because now it is reading from the credentials file rather than credential process)

Additional info:
Microsoft Windows [Version 10.0.18363.1500]
(c) 2019 Microsoft Corporation. All rights reserved.

H:\>aws sts get-caller-identity --profile legacy --debug
2021-05-07 09:11:50,185 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.2 Python/3.8.8 Windows/10 exe/AMD64
2021-05-07 09:11:50,185 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['sts', 'get-caller-identity', '--profile', 'legacy', '--debug']
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x00000265BFE4D430>
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x00000265BFCBE1F0>
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x00000265BF463940>
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x00000265BF46AA60>
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x00000265BFE8CE50>
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x00000265BFD09040>
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x00000265BFE8C0D0>
2021-05-07 09:11:50,385 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\awscli\data\cli.json
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x00000265BFDBB040>
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x00000265BFDBBB80>
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x00000265BFDBBAF0>
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x00000265BFDBBCA0>
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x00000265BFDBBC10>
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x00000265BFF265C0>
2021-05-07 09:11:50,385 - MainThread - botocore.session - DEBUG - Setting config variable for profile to 'legacy'
2021-05-07 09:11:50,385 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.2 Python/3.8.8 Windows/10 exe/AMD64 prompt/off
2021-05-07 09:11:50,385 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['sts', 'get-caller-identity', '--profile', 'legacy', '--debug']
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x00000265BFE4DA60>
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x00000265BF1FF280>
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x00000265BFEE88B0>
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x00000265BF1F8670>
2021-05-07 09:11:50,385 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x00000265BF261EE0>
2021-05-07 09:11:50,401 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-05-07 09:11:50,401 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2021-05-07 09:11:50,401 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x00000265BFD04EE0>
2021-05-07 09:11:50,401 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x00000265BFCBC0D0>
2021-05-07 09:11:50,586 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\botocore\data\sts\2011-06-15\service-2.json
2021-05-07 09:11:50,586 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sts: calling handler <function add_waiters at 0x00000265BFE8C0D0>
2021-05-07 09:11:50,755 - MainThread - awscli.clidriver - DEBUG - OrderedDict()
2021-05-07 09:11:50,755 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_streaming_output_arg at 0x00000265BFE82040>
2021-05-07 09:11:50,755 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_cli_input_json at 0x00000265BF26C790>
2021-05-07 09:11:50,755 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_cli_input_yaml at 0x00000265BF26CA60>
2021-05-07 09:11:50,755 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function unify_paging_params at 0x00000265BFCBE820>
2021-05-07 09:11:50,949 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\botocore\data\sts\2011-06-15\paginators-1.json
2021-05-07 09:11:50,949 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_generate_skeleton at 0x00000265BFDB15E0>
2021-05-07 09:11:50,949 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sts.get-caller-identity: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x00000265BFFBC130>>
2021-05-07 09:11:50,949 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sts.get-caller-identity: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x00000265BFF63190>>
2021-05-07 09:11:50,949 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sts.get-caller-identity: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x00000265BFF631C0>>
2021-05-07 09:11:50,956 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sts.get-caller-identity.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x00000265BFF542E0>
2021-05-07 09:11:50,956 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sts.get-caller-identity.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x00000265BFF542E0>
2021-05-07 09:11:50,956 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sts.get-caller-identity.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x00000265BFF542E0>
2021-05-07 09:11:50,956 - MainThread - botocore.hooks - DEBUG - Event calling-command.sts.get-caller-identity: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x00000265BFFBC130>>
2021-05-07 09:11:50,956 - MainThread - botocore.hooks - DEBUG - Event calling-command.sts.get-caller-identity: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x00000265BFF63190>>
2021-05-07 09:11:50,956 - MainThread - botocore.hooks - DEBUG - Event calling-command.sts.get-caller-identity: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x00000265BFF631C0>>
2021-05-07 09:11:50,956 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2021-05-07 09:11:50,956 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2021-05-07 09:11:50,956 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2021-05-07 09:11:50,956 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2021-05-07 09:11:50,956 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: custom-process
2021-05-07 09:12:00,508 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli\clidriver.py", line 459, in main
  File "awscli\clidriver.py", line 594, in __call__
  File "awscli\clidriver.py", line 770, in __call__
  File "awscli\clidriver.py", line 897, in invoke
  File "botocore\session.py", line 808, in create_client
  File "botocore\session.py", line 426, in get_credentials
  File "botocore\credentials.py", line 1975, in load_credentials
  File "botocore\credentials.py", line 961, in load
  File "botocore\credentials.py", line 987, in _retrieve_credentials_using
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Expecting value: line 1 column 1 (char 0)

H:\>aws sts get-caller-identity --profile legacy --debug
2021-05-07 09:12:18,182 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.2 Python/3.8.8 Windows/10 exe/AMD64
2021-05-07 09:12:18,182 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['sts', 'get-caller-identity', '--profile', 'legacy', '--debug']
2021-05-07 09:12:18,372 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x000001FBA6F9C430>
2021-05-07 09:12:18,372 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x000001FBA6DDE1F0>
2021-05-07 09:12:18,374 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2021-05-07 09:12:18,374 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x000001FBA6D82940>
2021-05-07 09:12:18,374 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x000001FBA6D88A60>
2021-05-07 09:12:18,374 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x000001FBA6FACE50>
2021-05-07 09:12:18,374 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x000001FBA6E29040>
2021-05-07 09:12:18,374 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2021-05-07 09:12:18,374 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x000001FBA6FAC0D0>
2021-05-07 09:12:18,374 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\awscli\data\cli.json
2021-05-07 09:12:18,382 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x000001FBA6EDB040>
2021-05-07 09:12:18,382 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x000001FBA6EDBB80>
2021-05-07 09:12:18,382 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x000001FBA6EDBAF0>
2021-05-07 09:12:18,382 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x000001FBA6EDBCA0>
2021-05-07 09:12:18,382 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x000001FBA6EDBC10>
2021-05-07 09:12:18,382 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x000001FBA70463C0>
2021-05-07 09:12:18,382 - MainThread - botocore.session - DEBUG - Setting config variable for profile to 'legacy'
2021-05-07 09:12:18,382 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.2 Python/3.8.8 Windows/10 exe/AMD64 prompt/off
2021-05-07 09:12:18,382 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['sts', 'get-caller-identity', '--profile', 'legacy', '--debug']
2021-05-07 09:12:18,382 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x000001FBA6F9CA60>
2021-05-07 09:12:18,382 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x000001FBA631F280>
2021-05-07 09:12:18,382 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x000001FBA70068B0>
2021-05-07 09:12:18,382 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x000001FBA6318670>
2021-05-07 09:12:18,382 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x000001FBA6381EE0>
2021-05-07 09:12:18,392 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-05-07 09:12:18,392 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2021-05-07 09:12:18,392 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x000001FBA6E24EE0>
2021-05-07 09:12:18,392 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x000001FBA6DDC0D0>
2021-05-07 09:12:18,570 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\botocore\data\sts\2011-06-15\service-2.json
2021-05-07 09:12:18,570 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sts: calling handler <function add_waiters at 0x000001FBA6FAC0D0>
2021-05-07 09:12:18,755 - MainThread - awscli.clidriver - DEBUG - OrderedDict()
2021-05-07 09:12:18,755 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_streaming_output_arg at 0x000001FBA6FA2040>
2021-05-07 09:12:18,755 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_cli_input_json at 0x000001FBA638C790>
2021-05-07 09:12:18,755 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_cli_input_yaml at 0x000001FBA638CA60>
2021-05-07 09:12:18,755 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function unify_paging_params at 0x000001FBA6DDE820>
2021-05-07 09:12:18,948 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\botocore\data\sts\2011-06-15\paginators-1.json
2021-05-07 09:12:18,948 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sts.get-caller-identity: calling handler <function add_generate_skeleton at 0x000001FBA6ED15E0>
2021-05-07 09:12:18,948 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sts.get-caller-identity: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x000001FBA7082190>>
2021-05-07 09:12:18,948 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sts.get-caller-identity: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x000001FBA70821C0>>
2021-05-07 09:12:18,948 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sts.get-caller-identity: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x000001FBA70DB220>>
2021-05-07 09:12:18,948 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sts.get-caller-identity.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000001FBA70752E0>
2021-05-07 09:12:18,948 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sts.get-caller-identity.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000001FBA70752E0>
2021-05-07 09:12:18,948 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sts.get-caller-identity.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x000001FBA70752E0>
2021-05-07 09:12:18,948 - MainThread - botocore.hooks - DEBUG - Event calling-command.sts.get-caller-identity: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x000001FBA7082190>>
2021-05-07 09:12:18,948 - MainThread - botocore.hooks - DEBUG - Event calling-command.sts.get-caller-identity: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x000001FBA70821C0>>
2021-05-07 09:12:18,948 - MainThread - botocore.hooks - DEBUG - Event calling-command.sts.get-caller-identity: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x000001FBA70DB220>>
2021-05-07 09:12:18,948 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2021-05-07 09:12:18,948 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2021-05-07 09:12:18,956 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2021-05-07 09:12:18,956 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2021-05-07 09:12:18,956 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2021-05-07 09:12:18,956 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files\Amazon\AWSCLIV2\botocore\data\endpoints.json
2021-05-07 09:12:18,956 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x000001FBA5B40040>
2021-05-07 09:12:18,956 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.sts: calling handler <function add_generate_presigned_url at 0x000001FBA5AD33A0>
2021-05-07 09:12:18,966 - MainThread - botocore.endpoint - DEBUG - Setting sts timeout as (60, 60)
2021-05-07 09:12:18,966 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.sts.GetCallerIdentity: calling handler <function base64_decode_input_blobs at 0x000001FBA700A040>
2021-05-07 09:12:18,966 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.sts.GetCallerIdentity: calling handler <function generate_idempotent_uuid at 0x000001FBA5B53040>
2021-05-07 09:12:18,966 - MainThread - botocore.hooks - DEBUG - Event before-call.sts.GetCallerIdentity: calling handler <function inject_api_version_header_if_needed at 0x000001FBA5B548B0>
2021-05-07 09:12:18,966 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=GetCallerIdentity) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'aws-cli/2.2.2 Python/3.8.8 Windows/10 exe/AMD64 prompt/off command/sts.get-caller-identity'}, 'body': {'Action': 'GetCallerIdentity', 'Version': '2011-06-15'}, 'url': 'https://sts.us-east-1.amazonaws.com/', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x000001FBA70DBAC0>, 'has_streaming_input': False, 'auth_type': None}}
2021-05-07 09:12:18,966 - MainThread - botocore.hooks - DEBUG - Event request-created.sts.GetCallerIdentity: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x000001FBA70DBB80>>
2021-05-07 09:12:18,966 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sts.GetCallerIdentity: calling handler <function set_operation_specific_signer at 0x000001FBA5B4EEE0>
2021-05-07 09:12:18,966 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2021-05-07 09:12:18,966 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-www-form-urlencoded; charset=utf-8
host:sts.us-east-1.amazonaws.com
x-amz-date:20210507T131218Z
x-amz-security-token:"<redacted>"

content-type;host;x-amz-date;x-amz-security-token
<redacted>
2021-05-07 09:12:18,966 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20210507T131218Z
20210507/us-east-1/sts/aws4_request
48b9c36fef6ed84d108d922a763799b0cc34b3417af00ba8362b0d19390d3a77
2021-05-07 09:12:18,966 - MainThread - botocore.auth - DEBUG - Signature:
<redacted>
2021-05-07 09:12:18,966 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://sts.us-east-1.amazonaws.com/, headers={'Content-Type': b'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': b'aws-cli/2.2.2 Python/3.8.8 Windows/10 exe/AMD64 prompt/off command/sts.get-caller-identity', 'X-Amz-Date': b'20210507T131218Z', 'X-Amz-Security-Token': b'"<redacted>"', 'Authorization': b'AWS4-HMAC-SHA256 Credential=<redacted>/20210507/us-east-1/sts/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-security-token, Signature=<redacted>', 'Content-Length': '43'}>
2021-05-07 09:12:18,966 - MainThread - botocore.httpsession - DEBUG - Certificate path: C:\Program Files\Amazon\AWSCLIV2\botocore\cacert.pem
2021-05-07 09:12:18,966 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): sts.us-east-1.amazonaws.com:443
2021-05-07 09:12:19,329 - MainThread - urllib3.connectionpool - DEBUG - https://sts.us-east-1.amazonaws.com:443 "POST / HTTP/1.1" 200 470
2021-05-07 09:12:19,329 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-RequestId': '9a8609ff-3d56-478e-881a-2cc86a1d6e9a', 'Content-Type': 'text/xml', 'Content-Length': '470', 'Date': 'Fri, 07 May 2021 13:12:20 GMT'}
2021-05-07 09:12:19,329 - MainThread - botocore.parsers - DEBUG - Response body:
b'<GetCallerIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">\n  <GetCallerIdentityResult>\n    <Arn>arn:aws:sts::<redacted>:assumed-role/<redacted></Arn>\n    <UserId><redacted></UserId>\n    <Account><redacted></Account>\n  </GetCallerIdentityResult>\n  <ResponseMetadata>\n    <RequestId>9a8609ff-3d56-478e-881a-2cc86a1d6e9a</RequestId>\n  </ResponseMetadata>\n</GetCallerIdentityResponse>\n'
2021-05-07 09:12:19,329 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sts.GetCallerIdentity: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x000001FBA73784F0>>
2021-05-07 09:12:19,329 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2021-05-07 09:12:19,329 - MainThread - botocore.hooks - DEBUG - Event after-call.sts.GetCallerIdentity: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x000001FBA7378130>>
2021-05-07 09:12:19,329 - MainThread - awscli.formatter - DEBUG - RequestId: 9a8609ff-3d56-478e-881a-2cc86a1d6e9a
{
    "UserId": "<redacted>",
    "Account": "<redacted>",
    "Arn": "arn:aws:sts::<redacted>:assumed-role/<redacted>"
}

H:\>

**Comment by mbwilding** [comment]
https://github.com/aws-azure-login/aws-azure-login/pull/279

This will solve it.
