### ISSUE TITLE
Puppeteer issue on Docker MacOs M1

### ISSUE THREAD

**Issue by vvchistyakov** [aws-azure-login/aws-azure-login#197]
Hi, I saw the similar issue has already been there, however it was directly for NPM.
Can you build special Docker image for Docker engine on MacOs M1 architecture?

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Logging in with profile 'XXX'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
Error: Protocol error (Target.setDiscoverTargets): Target closed.
    at /aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:70:16)
    at Function.create (/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:117:26)
    at ChromeLauncher.launch (/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:103:56)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object._performLoginAsync (/aws-azure-login/lib/login.js:461:23)
    at async Object.loginAsync (/aws-azure-login/lib/login.js:324:30)`

**Comment by vignesh1992** [comment]
Hi, Do we have any solutions in place towards solving this mentioned issue?

**Comment by weiser** [comment]
I'm also on a mac m1 (`uname -m # => arm64`).  I tried specifying the am64 architecture when I ran docker (`docker -v # => Docker version 20.10.12, build e91ed5707e`), and it also did not work:

```
docker run --platform linux/amd64 --rm -it -v ~/.aws:/root/.aws sportradar/aws-azure-login
Logging in with profile 'default'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
Error: Protocol error (Target.setDiscoverTargets): Target closed.
    at /aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:70:16)
    at Function.create (/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:117:26)
    at ChromeLauncher.launch (/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:103:56)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object._performLoginAsync (/aws-azure-login/lib/login.js:461:23)
    at async Object.loginAsync (/aws-azure-login/lib/login.js:324:30)
```

**Comment by erechnikov** [comment]
I am also having the exact same error as above. Is there some workaround?

**Comment by vignesh1992** [comment]
Hi, workaround for this issue is as follows, 

- npm install -g aws-azure-login
- aws-azure-login --configure
- aws-azure-login --profile profile_name
- docker run --rm -it -v ~/.aws:/root/.aws sportradar/aws-azure-login --configure --profile profile_name

**Comment by jotshin** [comment]
I second @vignesh1992 and using the npm installed one solves this problem.

**Comment by migueleliasweb** [comment]
I'm also having the same problem. I'm not sure if it's related to the architecture though. 

It looks to me it's a connectivity problem due to the fact Docker is running in a VM and not in the host as in Linux.

That said, I tried running with `--privileged --network host` and still got a similar error.
