### ISSUE TITLE
Puppeteer error when using --no-prompt on windows

### ISSUE THREAD

**Issue by sethbacon** [aws-azure-login/aws-azure-login#57]
On Windows 10 1803
When using switch --no-prompt I get the following 9 out of 10 times:
Logging in with profile 'profile'...
Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (C:\Users\seth.bacon\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\ExecutionContext.js:349:13)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  -- ASYNC --
    at ElementHandle.<anonymous> (C:\Users\seth.bacon\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\helper.js:144:27)
    at Frame.click (C:\Users\seth.bacon\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\FrameManager.js:705:18)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\seth.bacon\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\helper.js:144:27)
    at Page.click (C:\Users\seth.bacon\AppData\Roaming\npm\node_modules\aws-azure-login\node_modules\puppeteer\lib\Page.js:932:29)
    at Object.handler (C:\Users\seth.bacon\AppData\Roaming\npm\node_modules\aws-azure-login\lib\login.js:68:24)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

When following through with prompts, it seems to work fine.

**Comment by sethbacon** [comment]
After a some other testing, it appears that no prompt option is sending data before puppeteer is ready to accept it. Is it possible to introduce a small delay?

**Comment by Wraiith32** [comment]
I am experiencing the same problem.

**Comment by chrisbrownie** [comment]
@sethbacon is on the money. Dropping `--no-prompt` has allowed me to work around this issue. @dtjohnson any thoughts on how this could be resolved?

**Comment by mahdi-hosseini** [comment]
I am a collaborator on this project, I will look into it

**Comment by chrisbrownie** [comment]
Have tested @Levence's fix and can confirm it works. Can we get this merged?

**Comment by m-rieke** [comment]
It seems to depend on the system and/or network if the time is enough. I added a parameter (a multiplicator) so that the user is able to increase the timeout

**Comment by hermitmaster** [comment]
Stale, closing.
