### ISSUE TITLE
Error: Node is either not visible or not an HTMLElement

### ISSUE THREAD

**Issue by ronniegane** [aws-azure-login/aws-azure-login#81]
Using `aws-azure-login@1.7.0` with `puppeteer@1.19.0`

I get this error intermittently, and I'm not sure what triggers it.
After entering my username, aws-azure-login fails with this error:
```
aws-azure-login --profile alinta
Logging in with profile 'alinta'...
? Username: Ronnie.Gane@alintaenergy.com.au
Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (/usr/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/JSHandle.js:199:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ElementHandle.click (/usr/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/JSHandle.js:265:20)
    at async DOMWorld.click (/usr/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/DOMWorld.js:367:5)
    at async Object.handler (/usr/lib/node_modules/aws-azure-login/lib/login.js:68:13)
  -- ASYNC --
    at ElementHandle.<anonymous> (/usr/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.click (/usr/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/DOMWorld.js:367:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.handler (/usr/lib/node_modules/aws-azure-login/lib/login.js:68:13)
  -- ASYNC --
    at Frame.<anonymous> (/usr/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.click (/usr/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Page.js:1031:29)
    at Object.handler (/usr/lib/node_modules/aws-azure-login/lib/login.js:68:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Using Node v12.10.0 (npm v6.11.3) on Ubuntu.
I've tried with other versions of node (v7.6.0) and still get the same error.

**Comment by kennethaasan** [comment]
Hi @ronniegane 

We (Sportradar) just took over the maintenance of this tool. I upgraded to 1.8.0 today with an upgraded puppeteer version. We are many people in Sportradar using this tool on 1.7.0 without that problem. Can you try to run it with `--mode` set to gui or debug and try to find any problems?

**Comment by ronniegane** [comment]
Sorry, took me a while to be able to reproduce it with the `--mode debug` flag. What I've found is that sometimes the CLI username prompt comes up before the sign-in page is fully loaded. And so if you're quick to hit enter on your default name, I guess it tries to write to a username input field that isn't there yet.

What I mean is when the debug browser window first opens, I get this screen:
![image](https://user-images.githubusercontent.com/7067973/66826950-296d0480-efaa-11e9-9682-01bdbf85c81c.png)

And after a second it goes to this one:
![image](https://user-images.githubusercontent.com/7067973/66827135-95e80380-efaa-11e9-98d3-cb79032fbd3a.png)


But if I submit my username before the second page is loaded, I get the error
```
Error: Node is either not visible or not an HTMLElement
```

I'm not sure if this is unique to how my company has set up their AWS login process, or an issue other people could get as well.

As for a fix, would it be possible to delay the `Username: ` prompt until the page has finished loading?

**Comment by NeQuissimus** [comment]
I can confirm this is indeed happening. It seems particularly flaky on slow networks.

**Comment by kennethaasan** [comment]
I see. Sounds like we should look into the puppeteer API and wait for the page to be ready. If you could create a PR that would be great. Not sure when I have time to look into this myself.

**Comment by ghost** [comment]
any updates to this? still getting it, especially when using with --no-prompt

**Comment by RaviAtRACGP** [comment]
Any updates on this?? its happening for us too. We ran it on debug following is what we got . Note password is not prompting.

2020-08-04T03:49:30.785Z aws-azure-login Not prompting user for username
2020-08-04T03:49:30.785Z aws-azure-login Focusing on username input
2020-08-04T03:49:30.787Z aws-azure-login Request: https://autologon.microsoftazuread-sso.com/***/winauth/ssoprobe?client-request-id=2c36e88e-8cdf-42f3-9f58-540c858ad8fd&_=1596512970770
2020-08-04T03:49:30.791Z aws-azure-login Clearing input
2020-08-04T03:49:30.907Z aws-azure-login Typing username
2020-08-04T03:49:31.337Z aws-azure-login Request: https://login.microsoftonline.com/common/instrumentation/dssostatus
2020-08-04T03:49:31.479Z aws-azure-login Submitting form
Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/JSHandle.js:217:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  -- ASYNC --
    at ElementHandle.<anonymous> (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.click (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/DOMWorld.js:367:18)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  -- ASYNC --
    at Frame.<anonymous> (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.click (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Page.js:1037:29)
    at Object.handler (/usr/local/lib/node_modules/aws-azure-login/lib/login.js:77:24)
    at <anonymous>

**Comment by kennethaasan** [comment]
It looks the error happens close to https://github.com/sportradar/aws-azure-login/blob/main/src/login.ts#L94
You can try to tweak the code and console.log to check what's going on. Maybe increase the 500ms delay and see if that works for you. I'm happy to take a PR if you're able to fix it.

**Comment by koalarisms** [comment]
Hello 👋 

I'm relatively new here, but I have been using the aws-azure-login tool for a while now. This particular problem has become quite painful to live with so I thought I'd have a crack at fixing it for both myself and everyone else dealing with it.

Looking at the previous comments and reproducing the problem (on my machine... hah), what I have found telling is 'where' it appears to be failing - during the 'Submitting form' step as shown below

```
2020-08-05T09:18:07.933Z aws-azure-login Focusing on username input
2020-08-05T09:18:07.937Z aws-azure-login Clearing input
2020-08-05T09:18:08.049Z aws-azure-login Typing username
2020-08-05T09:18:08.580Z aws-azure-login Submitting form
Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (<sanitised_path>\aws-azure-login-2.1.0\node_modules\puppeteer\lib\JSHandle.js:216:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  -- ASYNC --
    at ElementHandle.<anonymous> (<sanitised_path>\aws-azure-login-2.1.0\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.click (<sanitised_path>\aws-azure-login-2.1.0\node_modules\puppeteer\lib\DOMWorld.js:367:18)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  -- ASYNC --
    at Frame.<anonymous> (<sanitised_path>\aws-azure-login-2.1.0\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.click (<sanitised_path>\aws-azure-login-2.1.0\node_modules\puppeteer\lib\Page.js:1064:29)
    at Object.handler (<sanitised_path>\aws-azure-login-2.1.0\lib\login.js:75:24)
    at <anonymous>
```

Looking at where this debug statement is makes be believe that the error is potentially caused by an attempt to click the Submit button before it's actually ready / visible, even though the username field is, somehow, available for input in that moment. In some situations I've witnessed the same issue occurring on the username input field as well (as seen in previous comments) when the network is particularly slow, but I've found this much harder to reliably reproduce.

I will put in a PR with two additions that have fixed the problem for me as shown in a run through with these changes here -

```
2020-08-05T09:37:17.778Z aws-azure-login Found state: username input
2020-08-05T09:37:17.779Z aws-azure-login Not prompting user for username
2020-08-05T09:37:17.779Z aws-azure-login Waiting for username input to be visible
2020-08-05T09:37:17.786Z aws-azure-login Focusing on username input
2020-08-05T09:37:17.789Z aws-azure-login Clearing input
2020-08-05T09:37:17.930Z aws-azure-login Typing username
2020-08-05T09:37:18.501Z aws-azure-login Waiting for submit button to be visible
2020-08-05T09:37:18.505Z aws-azure-login Submitting form
2020-08-05T09:37:18.517Z aws-azure-login Request: https://aadcdn.msftauth.net/ests/2.1/content/images/marching_ants_white_166de53471265253ab3a456defe6da23.gif
2020-08-05T09:37:18.518Z aws-azure-login Request: https://aadcdn.msftauth.net/ests/2.1/content/images/marching_ants_b540a8e518037192e32c4fe58bf2dbab.gif
2020-08-05T09:37:18.519Z aws-azure-login Request: https://login.microsoftonline.com/common/GetCredentialType?mkt=en-US
2020-08-05T09:37:19.022Z aws-azure-login Waiting for submission to finish
2020-08-05T09:37:19.247Z aws-azure-login Request: https://aadcdn.msftauth.net/ests/2.1/content/images/marching_ants_white_166de53471265253ab3a456defe6da23.gif
2020-08-05T09:37:19.247Z aws-azure-login Request: https://aadcdn.msftauth.net/ests/2.1/content/images/marching_ants_b540a8e518037192e32c4fe58bf2dbab.gif
2020-08-05T09:37:19.250Z aws-azure-login Request: https://autologon.microsoftazuread-sso.com/itree.com.au/winauth/ssoprobe?client-request-id=<redacted>
2020-08-05T09:37:19.514Z aws-azure-login Request: https://login.microsoftonline.com/common/instrumentation/dssostatus
2020-08-05T09:37:19.804Z aws-azure-login Request: https://aadcdn.msftauth.net/ests/2.1/content/images/arrow_left_a9cc2824ef3517b6c4160dcf8ff7d410.svg
2020-08-05T09:37:19.809Z aws-azure-login Finished state: username input
2020-08-05T09:37:19.812Z aws-azure-login Found state: password input
2020-08-05T09:37:19.813Z aws-azure-login Prompting user for password
etc...
```

It's two blocks of code that make the process wait until the elements in question are visible before attempting to interact with them. Feedback is welcome on whether this approach is appropriate / safe / working and whether it will actually solve the problem for others.

**Comment by kennethaasan** [comment]
Released as v2.2.2. Let me know if that fixed this issue so we can close 🙏

**Comment by RaviAtRACGP** [comment]
Works 🙏🙏🙏🙏🙏 Thanks Guys. By the way i was trying to fix the issue but had a hard time getting the environment setup is there documentation here how to setup the environment?

**Comment by koalarisms** [comment]
The changes have been working well for me since pulling 2.2.2

I'm happy for this to be closed if there are no objections from the others.

**Comment by RaviAtRACGP** [comment]
I'm happy for this to be closed

**Comment by RaviAtRACGP** [comment]
Looks like this issue is back

2020-10-30T02:46:15.631Z aws-azure-login Loading login page in Chrome
2020-10-30T02:46:15.981Z aws-azure-login Enabling request interception
2020-10-30T02:46:15.983Z aws-azure-login Going to login page
2020-10-30T02:46:15.998Z aws-azure-login Request: https://login.microsoftonline.com/***/saml2?SAMLRequest=jZJNT8MwDIbv%2FIoq97RJWtouWidNIKRJgBBfB24hcSFSk4w45evXUzbQEAiEj7bzvH7t7GUfMUflhrVcjunen8PDCJiyZzd47MgYvQwKLUqvHKBMWl4sT46lyJl0kJRRSZFsddgRaxrOyqqsezprTUMrUfb0tq051YabmRCsbllDsmuIaIPvyISYXiKOsPKYlE9TiglGOaMlu2RCVrXk%2B3kt9m%2Fe%2B84Uon2EjvRqQCDZEhFimkgHwePoIF5AfLQars6PO3Kf0hplUaC989bn6glz5dRr8LkOrni3S7YO5cb63z7XMaSgw0AWe9mXmG9mj%2F%2FZlPqclSyaqm5FNQPa15WZlsQ1VaUWdAa6KQ00LZR8XmzR3%2FS2Vzqd6KvDszBY%2FZIdhehU%2Bl2c53yTsYb2m1YJTtlhaUwERLKYFz%2BhO9XP6tePsau%2BAQ%3D%3D
2020-10-30T02:46:16.282Z aws-azure-login Request: https://login.live.com/Me.htm?v=3
2020-10-30T02:46:16.296Z aws-azure-login Request: https://aadcdn.msftauth.net/shared/1.0/content/js/OldConvergedLogin_PCore_44nYPjXE6TrAgja6fktsbQ2.js
2020-10-30T02:46:16.439Z aws-azure-login Request: https://aadcdn.msftauth.net/shared/1.0/content/images/microsoft_logo_ee5c8d9fb6248c938fd0dc19370e90bd.svg
2020-10-30T02:46:16.441Z aws-azure-login Request: https://aadcdn.msftauth.net/shared/1.0/content/images/ellipsis_white_5ac590ee72bfe06a7cecfd75b588ad73.svg
2020-10-30T02:46:16.442Z aws-azure-login Request: https://aadcdn.msftauth.net/shared/1.0/content/images/ellipsis_grey_2b5d393db04a5e6e1f739cb266e65b4c.svg
2020-10-30T02:46:16.458Z aws-azure-login Request: https://aadcdn.msftauth.net/ests/2.1/content/cdnbundles/converged.v2.login.min_n9bhxdhar2wr_7g1qclnjg2.css
2020-10-30T02:46:16.459Z aws-azure-login Request: https://aadcdn.msftauth.net/ests/2.1/content/cdnbundles/ux.converged.login.strings-en.min_ttakztbsdnghb1lolry46a2.js
2020-10-30T02:46:16.488Z aws-azure-login Request: https://secure.aadcdn.microsoftonline-p.com/81d6b03a-ufxrwapjsd2affrp58cj63yweuh-zp83e8atdsgb9ru/logintenantbranding/0/illustration?ts=636788049243326046
2020-10-30T02:46:16.490Z aws-azure-login Request: https://secure.aadcdn.microsoftonline-p.com/81d6b03a-ufxrwapjsd2affrp58cj63yweuh-zp83e8atdsgb9ru/logintenantbranding/0/bannerlogo?ts=636788049255197036
2020-10-30T02:46:16.494Z aws-azure-login Request: https://aadcdn.msftauth.net/shared/1.0/content/images/marching_ants_white_166de53471265253ab3a456defe6da23.gif
2020-10-30T02:46:16.495Z aws-azure-login Request: https://aadcdn.msftauth.net/shared/1.0/content/images/marching_ants_b540a8e518037192e32c4fe58bf2dbab.gif
2020-10-30T02:46:16.504Z aws-azure-login Request: https://autologon.microsoftazuread-sso.com/***/winauth/ssoprobe?client-request-id=aa2bf5e5-30bc-4b97-8f8f-4b16134da994&_=1604025976499
2020-10-30T02:46:16.508Z aws-azure-login Found state: username input
2020-10-30T02:46:16.515Z aws-azure-login Not prompting user for username
2020-10-30T02:46:16.516Z aws-azure-login Focusing on username input
2020-10-30T02:46:16.532Z aws-azure-login Clearing input
2020-10-30T02:46:16.636Z aws-azure-login Typing username
2020-10-30T02:46:17.208Z aws-azure-login Submitting form
Error: Node is either not visible or not an HTMLElement
at ElementHandle._clickablePoint (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/JSHandle.js:217:13)
at
at process._tickDomainCallback (internal/process/next_tick.js:229:7)
-- ASYNC --
at ElementHandle. (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/helper.js:111:15)
at DOMWorld.click (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/DOMWorld.js:367:18)
at
at process._tickDomainCallback (internal/process/next_tick.js:229:7)
-- ASYNC --
at Frame. (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/helper.js:111:15)
at Page.click (/usr/local/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/Page.js:1037:29)
at Object.handler (/usr/local/lib/node_modules/aws-azure-login/lib/login.js:77:24)
at

**Comment by RaviAtRACGP** [comment]
@riley-t is it possible to make this timeout value a variable that could be overridden by an environment variable. Because this is breaking again and again due to Microsoft changes to login. Since we don't have much expertise in typescript we are stranded for weeks. It would be awesome if we could override this timeout value using a variable then we just have to play with the value to get it going.
